2014/10/28 22:59:24 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: could not find driver' in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:382
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(450): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(634): CApplication->getDb()
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(667): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1595): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\yii\framework\web\CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#8 C:\xampp\htdocs\yii\framework\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#9 C:\xampp\htdocs\yii\framework\web\CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#10 C:\xampp\htdocs\yii\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#11 C:\xampp\htdocs\yii\framework\zii\widgets\CBaseListView.php(111): CDataProvider->getData()
#12 C:\xampp\htdocs\yii\framework\zii\widgets\CListView.php(211): CBaseListView->init()
#13 C:\xampp\htdocs\yii\framework\web\CBaseController.php(147): CListView->init()
#14 C:\xampp\htdocs\yii\framework\web\CBaseController.php(172): CBaseController->createWidget('zii.widgets.CLi...', Array)
#15 C:\xampp\htdocs\class_plans\protected\views\classPlan\index.php(19): CBaseController->widget('zii.widgets.CLi...', Array)
#16 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#17 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#18 C:\xampp\htdocs\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#19 C:\xampp\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#20 C:\xampp\htdocs\class_plans\protected\controllers\ClassPlanController.php(160): CController->render('index', Array)
#21 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): ClassPlanController->actionIndex()
#22 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#23 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#24 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#25 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#26 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#27 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#28 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#29 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#30 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#31 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('classPlan')
#32 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#33 C:\xampp\htdocs\class_plans\index.php(15): CApplication->run()
#34 {main}
REQUEST_URI=/class_plans/index.php/aulas
HTTP_REFERER=http://localhost/class_plans/
---
2014/10/28 23:03:18 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: could not find driver' in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:382
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(450): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(634): CApplication->getDb()
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(667): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1595): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\yii\framework\web\CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#8 C:\xampp\htdocs\yii\framework\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#9 C:\xampp\htdocs\yii\framework\web\CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#10 C:\xampp\htdocs\yii\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#11 C:\xampp\htdocs\yii\framework\zii\widgets\CBaseListView.php(111): CDataProvider->getData()
#12 C:\xampp\htdocs\yii\framework\zii\widgets\CListView.php(211): CBaseListView->init()
#13 C:\xampp\htdocs\yii\framework\web\CBaseController.php(147): CListView->init()
#14 C:\xampp\htdocs\yii\framework\web\CBaseController.php(172): CBaseController->createWidget('zii.widgets.CLi...', Array)
#15 C:\xampp\htdocs\class_plans\protected\views\classPlan\index.php(19): CBaseController->widget('zii.widgets.CLi...', Array)
#16 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#17 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#18 C:\xampp\htdocs\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#19 C:\xampp\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#20 C:\xampp\htdocs\class_plans\protected\controllers\ClassPlanController.php(160): CController->render('index', Array)
#21 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): ClassPlanController->actionIndex()
#22 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#23 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#24 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#25 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#26 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#27 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#28 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#29 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#30 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#31 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('classPlan')
#32 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#33 C:\xampp\htdocs\class_plans\index.php(15): CApplication->run()
#34 {main}
REQUEST_URI=/class_plans/index.php/aulas
HTTP_REFERER=http://localhost/class_plans/
---
2014/10/28 23:04:14 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente.
' in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:382
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(450): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(634): CApplication->getDb()
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(667): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1595): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\yii\framework\web\CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#8 C:\xampp\htdocs\yii\framework\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#9 C:\xampp\htdocs\yii\framework\web\CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#10 C:\xampp\htdocs\yii\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#11 C:\xampp\htdocs\yii\framework\zii\widgets\CBaseListView.php(111): CDataProvider->getData()
#12 C:\xampp\htdocs\yii\framework\zii\widgets\CListView.php(211): CBaseListView->init()
#13 C:\xampp\htdocs\yii\framework\web\CBaseController.php(147): CListView->init()
#14 C:\xampp\htdocs\yii\framework\web\CBaseController.php(172): CBaseController->createWidget('zii.widgets.CLi...', Array)
#15 C:\xampp\htdocs\class_plans\protected\views\classPlan\index.php(19): CBaseController->widget('zii.widgets.CLi...', Array)
#16 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#17 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#18 C:\xampp\htdocs\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#19 C:\xampp\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#20 C:\xampp\htdocs\class_plans\protected\controllers\ClassPlanController.php(160): CController->render('index', Array)
#21 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): ClassPlanController->actionIndex()
#22 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#23 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#24 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#25 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#26 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#27 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#28 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#29 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#30 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#31 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('classPlan')
#32 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#33 C:\xampp\htdocs\class_plans\index.php(15): CApplication->run()
#34 {main}
REQUEST_URI=/class_plans/index.php/aulas
HTTP_REFERER=http://localhost/class_plans/
---
2014/10/28 23:12:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'NÃ£o foi possÃ­vel resolver a requisiÃ§Ã£o "css/templates/slate.png".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('css/templates/s...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\class_plans\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/class_plans/css/templates/slate.png
HTTP_REFERER=http://localhost/class_plans/index.php/aulas/update/8
---
2014/10/28 23:13:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'NÃ£o foi possÃ­vel resolver a requisiÃ§Ã£o "css/templates/slate.png".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('css/templates/s...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\class_plans\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/class_plans/css/templates/slate.png
HTTP_REFERER=http://localhost/class_plans/index.php/aulas/update/8
---
2014/10/28 23:13:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'NÃ£o foi possÃ­vel resolver a requisiÃ§Ã£o "js/tinymce/themes/modern/theme.min.js".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('js/tinymce/them...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\class_plans\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/class_plans/js/tinymce/themes/modern/theme.min.js
HTTP_REFERER=http://localhost/class_plans/index.php/aulas/update/8
---
2014/10/28 23:20:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'NÃ£o foi possÃ­vel resolver a requisiÃ§Ã£o "css/templates/slate.png".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('css/templates/s...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\class_plans\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/class_plans/css/templates/slate.png
HTTP_REFERER=http://localhost/class_plans/index.php/aulas/update/8
---
2014/10/28 23:20:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'NÃ£o foi possÃ­vel resolver a requisiÃ§Ã£o "css/templates/slate.png".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('css/templates/s...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\class_plans\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/class_plans/css/templates/slate.png
HTTP_REFERER=http://localhost/class_plans/index.php/aulas/update/8
---
2014/12/01 20:32:08 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[08006] [7] FATAL:  no pg_hba.conf entry for host "177.134.73.99", user "naxrqsynwxglpe", database "d92fgdr2b74dbh", SSL off' in C:\xampp\htdocs\class_plans\vendor\yii\framework\db\CDbConnection.php:382
Stack trace:
#0 C:\xampp\htdocs\class_plans\vendor\yii\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\htdocs\class_plans\vendor\yii\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\class_plans\vendor\yii\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\htdocs\class_plans\vendor\yii\framework\base\CApplication.php(450): CModule->getComponent('db')
#4 C:\xampp\htdocs\class_plans\vendor\yii\framework\db\ar\CActiveRecord.php(634): CApplication->getDb()
#5 C:\xampp\htdocs\class_plans\vendor\yii\framework\db\ar\CActiveRecord.php(1428): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\class_plans\vendor\yii\framework\db\ar\CActiveRecord.php(1484): CActiveRecord->getTableAlias(true)
#7 C:\xampp\htdocs\class_plans\protected\controllers\UserController.php(163): CActiveRecord->findByPk('2')
#8 C:\xampp\htdocs\class_plans\protected\controllers\UserController.php(59): UserController->loadModel('2')
#9 [internal function]: UserController->actionView('2')
#10 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(UserController), Array)
#11 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(UserController), Object(ReflectionMethod), Array)
#12 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#13 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#14 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#15 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#17 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#18 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\CController.php(291): CFilterChain->run()
#19 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\CWebApplication.php(282): CController->run('view')
#21 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/view')
#22 C:\xampp\htdocs\class_plans\vendor\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#23 C:\xampp\htdocs\class_plans\index.php(16): CApplication->run()
#24 {main}
REQUEST_URI=/class_plans/index.php/usuario/2
HTTP_REFERER=http://localhost/class_plans/
---
2014/12/01 21:03:22 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[08006] [7] could not translate host name "{$host}" to address: Unknown server error' in C:\xampp\htdocs\class_plans\vendor\yii\framework\db\CDbConnection.php:382
Stack trace:
#0 C:\xampp\htdocs\class_plans\vendor\yii\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\htdocs\class_plans\vendor\yii\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\class_plans\vendor\yii\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\htdocs\class_plans\vendor\yii\framework\base\CApplication.php(450): CModule->getComponent('db')
#4 C:\xampp\htdocs\class_plans\vendor\yii\framework\db\ar\CActiveRecord.php(634): CApplication->getDb()
#5 C:\xampp\htdocs\class_plans\vendor\yii\framework\db\ar\CActiveRecord.php(1428): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\class_plans\vendor\yii\framework\db\ar\CActiveRecord.php(1484): CActiveRecord->getTableAlias(true)
#7 C:\xampp\htdocs\class_plans\protected\controllers\ClassPlanController.php(185): CActiveRecord->findByPk('8')
#8 C:\xampp\htdocs\class_plans\protected\controllers\ClassPlanController.php(66): ClassPlanController->loadModel('8')
#9 [internal function]: ClassPlanController->actionView('8')
#10 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(ClassPlanController), Array)
#11 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(ClassPlanController), Object(ReflectionMethod), Array)
#12 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#13 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#14 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#15 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#17 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#18 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\CController.php(291): CFilterChain->run()
#19 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\CWebApplication.php(282): CController->run('view')
#21 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('classPlan/view')
#22 C:\xampp\htdocs\class_plans\vendor\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#23 C:\xampp\htdocs\class_plans\index.php(16): CApplication->run()
#24 {main}
REQUEST_URI=/class_plans/index.php/aulas/8
HTTP_REFERER=http://localhost/class_plans/index.php/usuario/2
---
2014/12/01 21:04:24 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[08006] [7] could not translate host name "dbname=" to address: Unknown server error' in C:\xampp\htdocs\class_plans\vendor\yii\framework\db\CDbConnection.php:382
Stack trace:
#0 C:\xampp\htdocs\class_plans\vendor\yii\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\htdocs\class_plans\vendor\yii\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\class_plans\vendor\yii\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\htdocs\class_plans\vendor\yii\framework\base\CApplication.php(450): CModule->getComponent('db')
#4 C:\xampp\htdocs\class_plans\vendor\yii\framework\db\ar\CActiveRecord.php(634): CApplication->getDb()
#5 C:\xampp\htdocs\class_plans\vendor\yii\framework\db\ar\CActiveRecord.php(1428): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\class_plans\vendor\yii\framework\db\ar\CActiveRecord.php(1484): CActiveRecord->getTableAlias(true)
#7 C:\xampp\htdocs\class_plans\protected\controllers\ClassPlanController.php(185): CActiveRecord->findByPk('8')
#8 C:\xampp\htdocs\class_plans\protected\controllers\ClassPlanController.php(66): ClassPlanController->loadModel('8')
#9 [internal function]: ClassPlanController->actionView('8')
#10 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(ClassPlanController), Array)
#11 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(ClassPlanController), Object(ReflectionMethod), Array)
#12 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#13 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#14 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#15 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#17 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#18 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\CController.php(291): CFilterChain->run()
#19 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\CWebApplication.php(282): CController->run('view')
#21 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('classPlan/view')
#22 C:\xampp\htdocs\class_plans\vendor\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#23 C:\xampp\htdocs\class_plans\index.php(16): CApplication->run()
#24 {main}
REQUEST_URI=/class_plans/index.php/aulas/8
HTTP_REFERER=http://localhost/class_plans/index.php/usuario/2
---
2015/03/03 03:00:42 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[08006] [7] FATAL:  autenticação do tipo password falhou para usuário "postgres"' in C:\xampp\htdocs\class_plans\vendor\yii\framework\db\CDbConnection.php:382
Stack trace:
#0 C:\xampp\htdocs\class_plans\vendor\yii\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\htdocs\class_plans\vendor\yii\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\class_plans\vendor\yii\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\htdocs\class_plans\vendor\yii\framework\cli\commands\MigrateCommand.php(442): CModule->getComponent('db')
#4 C:\xampp\htdocs\class_plans\vendor\yii\framework\cli\commands\MigrateCommand.php(451): MigrateCommand->getDbConnection()
#5 C:\xampp\htdocs\class_plans\vendor\yii\framework\cli\commands\MigrateCommand.php(482): MigrateCommand->getMigrationHistory(-1)
#6 C:\xampp\htdocs\class_plans\vendor\yii\framework\cli\commands\MigrateCommand.php(84): MigrateCommand->getNewMigrations()
#7 [internal function]: MigrateCommand->actionUp(Array)
#8 C:\xampp\htdocs\class_plans\vendor\yii\framework\console\CConsoleCommand.php(172): ReflectionMethod->invokeArgs(Object(MigrateCommand), Array)
#9 C:\xampp\htdocs\class_plans\vendor\yii\framework\console\CConsoleCommandRunner.php(71): CConsoleCommand->run(Array)
#10 C:\xampp\htdocs\class_plans\vendor\yii\framework\console\CConsoleApplication.php(92): CConsoleCommandRunner->run(Array)
#11 C:\xampp\htdocs\class_plans\vendor\yii\framework\base\CApplication.php(180): CConsoleApplication->processRequest()
#12 C:\xampp\htdocs\class_plans\vendor\yii\framework\yiic.php(33): CApplication->run()
#13 C:\xampp\htdocs\class_plans\protected\yiic.php(7): require_once('C:\\xampp\\htdocs...')
#14 {main}
---
2015/03/03 03:02:52 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[42P07]: Duplicate table: 7 ERRO:  relaÃ§Ã£o "token" jÃ¡ existe. The SQL statement executed was: CREATE TABLE "token" (
	"id" serial NOT NULL PRIMARY KEY,
	"name" character varying (255) NOT NULL
).
2015/03/02 23:21:26 [error] [php] Undefined variable: length (C:\xampp\htdocs\class_plans\protected\components\Helper.php:12)
Stack trace:
#0 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#1 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\filters\CFilterChain.php(133): SiteController->runAction()
#2 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#4 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\filters\CInlineFilter.php(58): SiteController->filterAccessControl()
#5 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#6 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#8 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\CWebApplication.php(282): SiteController->run()
#9 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#10 C:\xampp\htdocs\class_plans\vendor\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 C:\xampp\htdocs\class_plans\index.php(16): CWebApplication->run()
REQUEST_URI=/class_plans/index.php/
in C:\xampp\htdocs\class_plans\protected\components\Helper.php (12)
in C:\xampp\htdocs\class_plans\protected\controllers\SiteController.php (63)
in C:\xampp\htdocs\class_plans\index.php (16)
2015/03/02 23:30:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'O sistema nÃ£o foi capaz de encontrar a aÃ§Ã£o "udate3" solicitada.' in C:\xampp\htdocs\class_plans\vendor\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\CController.php(270): CController->missingAction('udate3')
#1 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\CWebApplication.php(282): CController->run('udate3')
#2 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('classPlan/udate...')
#3 C:\xampp\htdocs\class_plans\vendor\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\class_plans\index.php(16): CApplication->run()
#5 {main}
REQUEST_URI=/class_plans/index.php/aulas/udate3
---
2015/03/02 23:30:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'O sistema nÃ£o foi capaz de encontrar a aÃ§Ã£o "udate" solicitada.' in C:\xampp\htdocs\class_plans\vendor\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\CController.php(270): CController->missingAction('udate')
#1 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\CWebApplication.php(282): CController->run('udate')
#2 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('classPlan/udate')
#3 C:\xampp\htdocs\class_plans\vendor\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\class_plans\index.php(16): CApplication->run()
#5 {main}
REQUEST_URI=/class_plans/index.php/aulas/udate/3
---
2015/03/02 23:32:32 [error] [exception.CException] exception 'CException' with message 'A propriedade "ClassPlan.access_token" nÃ£o estÃ¡ definida.' in C:\xampp\htdocs\class_plans\vendor\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\class_plans\vendor\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('access_token')
#1 C:\xampp\htdocs\class_plans\protected\controllers\ClassPlanController.php(47): CActiveRecord->__get('access_token')
#2 [internal function]: ClassPlanController->{closure}(Object(CWebUser), Object(CAccessRule))
#3 C:\xampp\htdocs\class_plans\vendor\yii\framework\base\CComponent.php(617): call_user_func_array(Object(Closure), Array)
#4 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\auth\CAccessControlFilter.php(392): CComponent->evaluateExpression(Object(Closure), Array)
#5 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\auth\CAccessControlFilter.php(288): CAccessRule->isExpressionMatched(Object(CWebUser))
#6 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\auth\CAccessControlFilter.php(138): CAccessRule->isUserAllowed(Object(CWebUser), Object(ClassPlanController), Object(CInlineAction), '::1', 'GET')
#7 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#8 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#9 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#10 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#11 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\CController.php(291): CFilterChain->run()
#12 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\CWebApplication.php(282): CController->run('update')
#14 C:\xampp\htdocs\class_plans\vendor\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('classPlan/updat...')
#15 C:\xampp\htdocs\class_plans\vendor\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#16 C:\xampp\htdocs\class_plans\index.php(16): CApplication->run()
#17 {main}
REQUEST_URI=/class_plans/index.php/aulas/update/3?access_token=123
---
2015/03/03 03:35:40 [error] [php] require_once(C:\xampp\htdocs\class_plans\protected\migrations\m141019_183229_create_classplan_table.php): failed to open stream: No such file or directory (C:\xampp\htdocs\class_plans\vendor\yii\framework\cli\commands\MigrateCommand.php:428)
Stack trace:
#0 C:\xampp\htdocs\class_plans\vendor\yii\framework\cli\commands\MigrateCommand.php(145): MigrateCommand->migrateDown()
#1 unknown(0): MigrateCommand->actionDown()
#2 C:\xampp\htdocs\class_plans\vendor\yii\framework\console\CConsoleCommand.php(172): ReflectionMethod->invokeArgs()
#3 C:\xampp\htdocs\class_plans\vendor\yii\framework\console\CConsoleCommandRunner.php(71): MigrateCommand->run()
#4 C:\xampp\htdocs\class_plans\vendor\yii\framework\console\CConsoleApplication.php(92): CConsoleCommandRunner->run()
#5 C:\xampp\htdocs\class_plans\vendor\yii\framework\base\CApplication.php(180): CConsoleApplication->processRequest()
#6 C:\xampp\htdocs\class_plans\vendor\yii\framework\yiic.php(33): CConsoleApplication->run()
#7 C:\xampp\htdocs\class_plans\protected\yiic.php(7): require_once()

